### ISSUE TITLE
After Update to httpheader 1.0.7 a PHP Exception occurred on my site

### ISSUE THREAD

**Issue by deltapapa01** [zero-24/plg_system_httpheader#17]
Hi,
after update the plugin to 1.0.7, my sites reports the follow php error:

`A PHP Exception occurred on your site. Here you can find the stack trace:

Exception Type: Error
File: /var/www/vhosts/domain.de/root/cms/plugins/system/httpheader/httpheader.php
Line: 194
Message: Call to undefined method Joomla\CMS\Document\FeedDocument::getHeadData()

#0 /var/www/vhosts/domain.de/root/cms/libraries/joomla/event/event.php(70): PlgSystemHttpHeader->onAfterRender()
#1 /var/www/vhosts/domain.de/root/cms/libraries/joomla/event/dispatcher.php(160): JEvent->update(Array)
#2 /var/www/vhosts/domain.de/root/cms/libraries/src/Application/BaseApplication.php(108): JEventDispatcher->trigger('onafterrender', Array)
#3 /var/www/vhosts/domain.de/root/cms/libraries/src/Application/CMSApplication.php(1050): Joomla\CMS\Application\BaseApplication->triggerEvent('onAfterRender')
#4 /var/www/vhosts/domain.de/root/cms/libraries/src/Application/SiteApplication.php(778): Joomla\CMS\Application\CMSApplication->render()
#5 /var/www/vhosts/domain.de/root/cms/libraries/src/Application/CMSApplication.php(202): Joomla\CMS\Application\SiteApplication->render()
#6 /var/www/vhosts/domain.de/root/cms/index.php(49): Joomla\CMS\Application\CMSApplication->execute()
#7 {main}

Request information
GET variables

Array
(
    [format] => feed
    [type] => atom
)

POST variables

Array
(
)

COOKIE variables

Array
(
)

REQUEST variables

Array
(
    [format] => feed
    [type] => atom
    [Itemid] => 111
    [option] => com_content
    [view] => category
    [layout] => blog
    [id] => 10
    [limit] => 10
)

SERVER variables

Array
(
    [PATH] => /sbin:/usr/sbin:/bin:/usr/bin
    [PP_CUSTOM_PHP_INI] => /var/www/vhosts/system/domain.de/etc/php.ini
    [PP_CUSTOM_PHP_CGI_INDEX] => plesk-php73-fastcgi
    [SCRIPT_NAME] => /index.php
    [REQUEST_URI] => /notizen?format=feed&type=atom
    [QUERY_STRING] => format=feed&type=atom
    [REQUEST_METHOD] => GET
    [SERVER_PROTOCOL] => HTTP/1.0
    [GATEWAY_INTERFACE] => CGI/1.1
    [REDIRECT_URL] => /notizen
    [REDIRECT_QUERY_STRING] => format=feed&type=atom
    [REMOTE_PORT] => 53202
    [SCRIPT_FILENAME] => /var/www/vhosts/domain.de/root/cms/index.php
    [SERVER_ADMIN] => root@localhost
    [DOCUMENT_ROOT] => /var/www/vhosts/domain.de/root/cms
    [REMOTE_ADDR] => 157.55.39.178
    [SERVER_PORT] => 443
    [SERVER_ADDR] => 128.127.71.239
    [SERVER_NAME] => www.domain.de
    [SERVER_SOFTWARE] => Apache
    [SERVER_SIGNATURE] => 
    [HTTP_USER_AGENT] => Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_ACCEPT] => */*
    [HTTP_PRAGMA] => no-cache
    [HTTP_CACHE_CONTROL] => no-cache
    [HTTP_CONNECTION] => close
    [HTTP_X_ACCEL_INTERNAL] => /internal-nginx-static-location
    [HTTP_X_FORWARDED_FOR] => 157.55.39.178
    [HTTP_X_REAL_IP] => 157.55.39.178
    [HTTP_HOST] => www.domain.de
    [HTTPS] => on
    [UNIQUE_ID] => XWN6fYB-R@6BBFO9M4wBBBBBG
    [REDIRECT_STATUS] => 200
    [REDIRECT_HTTPS] => on
    [REDIRECT_HTTP_AUTHORIZATION] => 
    [REDIRECT_UNIQUE_ID] => XVN8fYB-R@8AAFO9M4wAAAAG
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1565752445.333
    [REQUEST_TIME] => 1565752445
)
`

WBR,
deltapapa

**Comment by zero-24** [comment]
Please apply this patch here by @snipersister https://github.com/zero-24/plg_system_httpheader/pull/16 and try again.

**Comment by deltapapa01** [comment]
Hi, thanks :-) Is it necessary to reinstall the patch or can I just replace the httpheader.php with the changed code?

**Comment by zero-24** [comment]
Release has been made thanks: https://github.com/zero-24/plg_system_httpheader/releases/tag/1.0.8
