### ISSUE TITLE
Admin Tools Exceptions Graph not working with HttpHeader 1.0.7

### ISSUE THREAD

**Issue by deltapapa01** [zero-24/plg_system_httpheader#18]
Hi,
after update to 1.0.7 my Exceptions Graph from Admin Tools not longer working:
![Anmerkung 2019-08-14 095157](https://user-images.githubusercontent.com/19833064/63003763-34f06200-be79-11e9-8db4-ba6a5dce7c69.jpg)

Disable the plugin solved the prob....

WBR,
deltapapa

**Comment by zero-24** [comment]
Hi,

can you show me the browser console messages of this sites?

**Comment by deltapapa01** [comment]
Hi, the httpheader.php from SniperSisters patch solved this prob too :-)
Thanks...

**Comment by zero-24** [comment]
Release has been made thanks: https://github.com/zero-24/plg_system_httpheader/releases/tag/1.0.8
