### ISSUE TITLE
RSS feeds not working anymore after enabling the plugin

### ISSUE THREAD

**Issue by jeckodevelopment** [zero-24/plg_system_httpheader#24]
Hello :)
I'm almost sure that is due to my plugin configuration.
So a bit of information about the scenario.

### RSS Feeds
they are generated for Joomla categories of articles.
URL format is the following
The site is using "**Legacy Routing**".

`[SITE URL]/notizie.feed?type=rss`

----

### Plugin Configuration

- X-Frame-Options: Enabled
- X-XSS-Protection: Enabled
- Referrer-Policy: `no-referrer-when-downgrade`

Additional HTTP headers:
Header: `Feature-Policy`
Value: `geolocation 'none'`
Site-only

----

- HTTP Strict Transport Security (HSTS): Enabled
- Max Time: 31536000
- Subdomains: enabled
- Preload: disabled

----

CSP: Enabled
Report-Only: Disabled
Script hashes: Disabled
Style hashes: Disabled

**Policies enabled:**

- default-src
- script-src
- style-src
- img-src
- font-src
- media-src
- form-action
- upgrade-insecure-requests
- block-all-mixed-content

----

What is wrong? :)
Disabling the plugin restore feed functionality.

**Comment by zero-24** [comment]
Ok found the Problem... patched here: https://github.com/zero-24/plg_system_httpheader/commit/c76db38cb0798f77b61c81b0845e277bcd50afdb update to 1.0.10 incoming sorry to the trouble caused. :(

**Comment by jeckodevelopment** [comment]
No worries!
Thanks for fixing it so quickly! :)
