### ISSUE TITLE
Update from 1.0.11 to 1.0.12 does not go through

### ISSUE THREAD

**Issue by deltapapa01** [zero-24/plg_system_httpheader#27]
Hi,
I think a small bug has crept in. The update from 1.0.11 to 1.0.12 runs smoothly, but I still see it as an update in the backend afterwards. Under Extensions / Manage, the plugin is also shown to me after 1.0.11 after the update.

WBR,
deltapapa

**Comment by zero-24** [comment]
Just moved, the issue. will take a look.

**Comment by zero-24** [comment]
please try again the update it seams i uploaded the wrong package to the release, that should be fixed now.

**Comment by deltapapa01** [comment]
okay, the update works, but I get an error message: "Die Prüfsummenprüfung ist fehlgeschlagen! Bitte den verwendeten Update-Server überprüfen!"

**Comment by zero-24** [comment]
hmm can you please download the package to your PC and check that you get this `499aa7897a9640e5491d51375360d8267d659a6a4f3e5148bf7a06af7d57715aa9ac4c1ddadb2f197e0e9e230bcecd5be16ed6d0110a5962b43c3a0155ac4473` an hash sum of that file here: 
https://github.com/zero-24/plg_system_httpheader/releases/download/1.0.12/plg_system_httpheader.zip

 I can only think of an cache issue at GitHub than
```shell
wget https://github.com/zero-24/plg_system_httpheader/releases/download/1.0.12/plg_system_httpheader.zip
sha512sum plg_system_httpheader.zip
```

when that worked please try again.

**Comment by zero-24** [comment]
Just did an test update from 1.0.11 to the new 1.0.12 and it worked without issues and does not pop up again. Can you confirm this on your end too?

**Comment by deltapapa01** [comment]
Hi Zero, yes, now it works without a error. Thank you very much and "bleib gesund"!!!

**Comment by zero-24** [comment]
Thanks for checking. Bleib du auch gesund :-)
