### ISSUE TITLE
Headers added only to admin section

### ISSUE THREAD

**Issue by peldax** [zero-24/plg_system_httpheader#30]
Hello,

I have no experience using Joomla, but I ended up supporting one site powered by it... Today I upgraded to 3.9 from 3.5 and made some polishing. I wanted to add some security headers so I came across this plugin. Everything is working really well in administration part, but no headers are added for front end section. Would you please give me some pointer where do I need to look to find the cause?

Thank you, for your response and for the useful plugin.

**Comment by zero-24** [comment]
Hi, can you share your plugin configuration as screenshot?

Usually the header should be set for the frontend and the backend.

**Comment by peldax** [comment]
- Here is the configuration, I just enabled the basic options. 

![Screenshot_2020-07-27_22-03-08](https://user-images.githubusercontent.com/10790033/88586707-0d2be700-d055-11ea-8947-6985fea2d811.png)
![Screenshot_2020-07-27_22-02-48](https://user-images.githubusercontent.com/10790033/88586710-0dc47d80-d055-11ea-9d12-8f47d4b0e20a.png)
![Screenshot_2020-07-27_22-02-34](https://user-images.githubusercontent.com/10790033/88586711-0e5d1400-d055-11ea-82ce-fd95e05cc3e5.png)

- Here are the headers from chrome, first one from administration and second from public part.

![Screenshot_2020-07-27_22-05-36](https://user-images.githubusercontent.com/10790033/88586935-77448c00-d055-11ea-9d18-b1809ad3eedf.png)
![Screenshot_2020-07-27_22-05-07](https://user-images.githubusercontent.com/10790033/88586937-77dd2280-d055-11ea-89db-9453d82f12e5.png)

**Comment by zero-24** [comment]
Hmm even the expires header  from the frontend seems to be not a joomla one. Could it be that there is a custom frontend build on that site?

Is that site cached somehow?

What happen when you set a header via the .htaccess file?

**Comment by peldax** [comment]
Thank you for your response. 

I removed all the caches (which I managed to find) after changes in the configuration. When I set the header via .htaccess file using "Header Set ..." command, the header is inserted correctly.

**Comment by zero-24** [comment]
hmm this does not make sense to me as the plugin is setup correctly. Can you send me the URL you are working on? Maybe I get an idea from that to check why it is not set in the frontend.

**Comment by peldax** [comment]
Yes, its [atfinstav.cz](https://atfinstav.cz)

**Comment by zero-24** [comment]
hmm i have not worked out yet why it is not added there.

Is there maybe another extension that touches the headers or does the template have something like that?

It looks like that there is a different expires header than the default one:
`expires: Wed, 29 Jul 2020 19:06:17 GMT`
it should be
`expires: Wed, 17 Aug 2005 00:00:00 GMT`

And that some kind of header landed in the final response too:
`expect-ct: max-age=12345; enforce`

It seems that the later one is set via htaccess? given that this is set on the backend too.

To rule out the tempalte can you check what happes when you switch to the core default tempalte?

**Comment by zero-24** [comment]
Any update here @peldax? To me it seems not to be a problem with the plugin but some more general stuff happend on that specific site concerning http headers.

**Comment by peldax** [comment]
Hello, I haven't got time to dig into it yet, there is a lot of custom template code. Its definitely not a plugin problem, feel free to close the issue. Thank you for ensuring that the setup is correct and giving me pointers to look into template files.

**Comment by zero-24** [comment]
Ok will close here than. Feel free to update this thread with the solution when you get it.
