### ISSUE TITLE
[enhancement] Add support for Permissions-Policy

### ISSUE THREAD

**Issue by raramuridesign** [zero-24/plg_system_httpheader#31]
Hi 
Would it be possible to add support for Permissions-Policy

Permissions Policy is a new header that allows a site to control which features and APIs can be used in the browser.
https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

Matthew

**Comment by zero-24** [comment]
Hi, there is already general support for Permissions-Policy since [1.0.13](https://github.com/zero-24/plg_system_httpheader/releases/tag/1.0.13)

https://github.com/zero-24/plg_system_httpheader/blob/master/httpheader.php#L58

**Comment by raramuridesign** [comment]
The latest scan we did - shows this to be an issue.
Is there a special setup to get this working- if yes, how do we do this?
Matthew

**Comment by zero-24** [comment]
You can set the Permission-Policy using the `Force HTTP Headers` option of the plugin similiar to the Feature-Policy.
![image](https://user-images.githubusercontent.com/2596554/95956423-8d651b80-0dfe-11eb-8a51-3f562da92d74.png)

**Comment by raramuridesign** [comment]
Thanks.
I actually worked this out, just to get the error away. I see where this is going so thanks.
M.

**Comment by raramuridesign** [comment]
Just a note, this doc refers to the list of allowed features, which will relate to this new permissions policy.
https://www.smashingmagazine.com/2018/12/feature-policy/
Might be worth having in the docs so users are aware of the list that can be added.

**Comment by zero-24** [comment]
Sorry that it took that long to come back to you. I have just added some docs to the readme. I choosen to point to the mozilla MDM you can see that here: https://github.com/zero-24/plg_system_httpheader/commit/8c9261d63373d91a295548cf32ef311674cc64c5

**Comment by raramuridesign** [comment]
Thank you ;-)
