### ISSUE TITLE
purchased Template ignoring your plugin

### ISSUE THREAD

**Issue by thimmey** [zero-24/plg_system_httpheader#34]
Hello Zero24,

I've installed your plugin and noticed it is not taken into account when using a bought template. when activating the default template it works as expected.

Is there any code which a template would need to have in order to consider your plugin and get the expected outcome?

Kind regards,
Tim

**Comment by zero-24** [comment]
Hi @thimmey 

there should be no template specific code required. This plugin should work independed of any template. Can you confirm that the plugin is enabled and that the settings are activated too?

**Comment by zero-24** [comment]
Will close this issue for now. Feel free to re open when you still have problems with that template.
