### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Heklaterriol** [zero-24/plg_system_httpheader#37]
Hi, just noted, that in all the langauges the language strings are missing for:

PLG_SYSTEM_HTTPHEADER_XFRAMEOPTIONS_DESC
PLG_SYSTEM_HTTPHEADER_XXSSPROTECTION_DESC
PLG_SYSTEM_HTTPHEADER_XCONTENTTYPEOPTIONS_DESC
PLG_SYSTEM_HTTPHEADER_REFERRERPOLICY_DESC

Thank you

![HttpHeader](https://user-images.githubusercontent.com/28540581/128888106-d373e1ee-8dd2-4e54-a1c8-95e14d9fc48b.jpg)

**Comment by zero-24** [comment]
Hi, thanks for the report on a quick look it seems I have removed the strings but not the XML settings. Will check where we still need them and add them back where needed.

**Comment by zero-24** [comment]
Finally i have just [added the translations back](https://github.com/zero-24/plg_system_httpheader/commit/30d4617a239c37a7351578330f8bba931c997e8c ) and pushed [1.0.16](https://github.com/zero-24/plg_system_httpheader/releases/tag/1.0.16) with the changes.

Thanks @Heklaterriol
