### ISSUE TITLE
Testing HttpHeader Plugin

### ISSUE THREAD

**Issue by hkeyzer** [zero-24/plg_system_httpheader#39]
Hi,

Just coming up to speed on response headers - all new to me. So looked around for potential solutions to apply header security to my pre V4 Joomla sites. So proceeded to test this "http header" plugin on one of my sites: nzjoomla.co.nz
PHP: 7.3.25
Joomla: 3.10.2

I downloaded and installed the plugin - enabled default and then checked it at: https://securityheaders.com which gave it a poor result - no headers.

However - no security headers appeared. So changed the template to a Joomla default and re-tested, again no headers appeared.
Removed and the reinstalled the plugin (enabled) and retested - no change.

Would be keen to get this plugin successfully tested on my joomla installation so I can look at applying it elsewhere. So hope you can assist.

Thanks
Henk

**Comment by zero-24** [comment]
Hmm interesting can you show me the plugin configuration you have in place?

**Comment by hkeyzer** [comment]
Hi,

Thanks for getting back to me - attached are images as requested.
Update I also tested using the default joomla templates Beez and Protostar same result.
So hopefully it relates to the configuration - but I have simply left it as default.

Cheers

![http_002](https://user-images.githubusercontent.com/1869748/136473679-e25cc98d-ed50-4275-827c-3021d7be0780.JPG)
![http_003](https://user-images.githubusercontent.com/1869748/136473681-33a0e7f4-2628-485c-9a9d-22e019c32656.JPG)
![http_001](https://user-images.githubusercontent.com/1869748/136473683-83485337-e6a7-4722-88bf-13ed479b77ba.JPG)

**Comment by hkeyzer** [comment]
Hi,

Reinstalled the plugin this morning and now I am getting a better result. The first four default headers are showing now.
So I  can move on.

Cheers
Henk

**Comment by hkeyzer** [comment]
![change](https://user-images.githubusercontent.com/1869748/136475455-aae9a497-fc9a-4c32-bd5d-4b395af2d1d3.JPG)

**Comment by zero-24** [comment]
Right the screenshot shows what expected now. As you have not enabled the settings for hsts and the csp. So this here can be closed?

**Comment by hkeyzer** [comment]
Hi,
Sorry reluctant to close this issue - I carried out further testing and eventually I got hsts and csp working correctly also.
But a few days later decided to rescan the site while I tried installing on another domain. 
When I rescanned the site I found it failed all tests again, tested at: https://securityheaders.com 
Although I hadn't changed anything on the site:

![later](https://user-images.githubusercontent.com/1869748/136856920-0bc51b75-755e-4d3a-b6c6-d5d31b23886e.JPG)

However I decided to retest at: https://www.serpworx.com/check-security-headers/
and got a reasonably clean bill of health.

Is anyway I can check the header status myself to confirm if the "tester" I am using is providing a false result?

Thanks
Henk

**Comment by zero-24** [comment]
Hmm interesting i never had any problems with Securityheaders.com

> Is anyway I can check the header status myself to confirm if the "tester" I am using is providing a false result?

Yes you can check the headers set by the site using the network tab within the browser console (location depends on your browser)
