### ISSUE TITLE
Adding a ftp subdomain to CSP

### ISSUE THREAD

**Issue by migboisvenue** [zero-24/plg_system_httpheader#40]
Hi,

I am trying to add a CSP to the subdomain ftp.[my-domain] and I was wondering how I can do it from the plugin configuration settings or if I can do it at all. I'm very new to all this, so sorry if it's an easy answer.

Thank you,

**Comment by zero-24** [comment]
Hi,

please clarify do you want to add the `ftp.[my-domain]` to the allowed list of domains for a directive like img-src or similiar?

Or do you want to deploy a dedicated CSP rule for the ftp subdomain?

**Comment by migboisvenue** [comment]
Hi,

I would think to deploy a dedicated CSP rule for the ftp subdomain. I attached the screenshot of the warning that we have for our website

![image001](https://user-images.githubusercontent.com/99493639/153870575-2698c1c6-230d-42d4-b99c-81c2d62e54be.png)
![image002 (1)](https://user-images.githubusercontent.com/99493639/153870584-2d8d4ad4-bf21-4b2d-ae13-92e173f116d9.png)
.

**Comment by zero-24** [comment]
> I would think to deploy a dedicated CSP rule for the ftp subdomain. I attached the screenshot of the warning that we have for our website

As long as there is no joomla application running on that ftp. subdomain you have to use the .htaccess file to setup your CSP and HSTS rules.

```
<IfModule mod_headers.c>
       # Strict-Transport-Security
	Header always set Strict-Transport-Security "max-age=31536000"
	# Content-Security-Policy
	Header always set Content-Security-Policy "[CSP rule goes here]"
</IfModule>

```

When you are running a joomla application you can install this plugin and setup the CSP header.

**Comment by migboisvenue** [comment]
For the HSTS rule, do I need to include subdomains as well? or do I simply write this line and it will include them by default:

Header always set Strict-Transport-Security "max-age=31536000"

**Comment by zero-24** [comment]
Adding the `includeSubdomains` would instruct the client which contacted to one site to always load the sudomains with HTTPs too.

You can find more details about it here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

But that sounds like you could solve your question so we can close this issue here?

**Comment by zero-24** [comment]
Will close this issue here now. Thanks
