### ISSUE TITLE
Removing headers

### ISSUE THREAD

**Issue by ramblerswebs** [zero-24/plg_system_httpheader#42]
Hi 
PHP adds the header X-Powered-By and it seems to be recommended not to send this information.
Would it be possible to have an option to remove this header and perhaps any others that are not recommended?

**Comment by zero-24** [comment]
Hmm i see your point but i'm not sure whether it matches the scope of this plugin. the "remove header" feature of PHP from my understanding only apply to headers set by php and not to the things you are getting from your webserver. There the htaccess is the better choice. And to get rid of the php version header there is even a setting within php itself. so such a feature would only be a bandage for an wrongly configured server and only applies to some of the headers set to your site.

**Comment by ramblerswebs** [comment]
I am new to this subject so can I ask a stupid question which is where is the best place to remove the X-Powered-By header
Am I correct that you think it best to do it via a php.ini file?

**Comment by zero-24** [comment]
Yes the PHP ini file or via htaccess.

**Comment by zero-24** [comment]
Closing as out of scope for this extension. thanks
