### ISSUE TITLE
Missing Headers - Permissions-Policy

### ISSUE THREAD

**Issue by marvays** [zero-24/plg_system_httpheader#44]
Hi. I am using J 3.5 and System - HTTPHeaders 1.0.17

I don't have a problem on other sites... just here. What can cause the PP not to be seen in the code? Can it cause tempalte? I'm not a security expert, I install this plugin automatically when I start a new website and I use the same settings for all websites (I have it saved in pspad).

![Scan results for https___www orsczech cz (1)](https://user-images.githubusercontent.com/72960077/209285419-3b695e6b-c2f2-446d-97fa-0963c7955c21.png)
![Scan results for https___www orsczech cz](https://user-images.githubusercontent.com/72960077/209285421-fa5af395-cc47-4a7f-8fec-1344a56bfe53.png)
![Pluginy_ System - HTTPHeaders - ORS CZECH - Administrace](https://user-images.githubusercontent.com/72960077/209285426-4cec288e-d58d-499f-8562-4abca9546fab.png)

**Comment by zero-24** [comment]
Hi, the header is supported by the plugin (https://github.com/zero-24/plg_system_httpheader/blob/master/httpheader.php#L58)

But on your screenshot it looks like you have an additional `#` before the permission policy setting? Please try to remove this and let the check run again.

**Comment by zero-24** [comment]
Ps please Upgrade your Joomla to 3.10.11 as soon as possible Joomla 3.5 has known and publicly documented Security issues ;⁠-⁠)

**Comment by marvays** [comment]
I have 3.10.11
Maybe AdminTools?

**Comment by zero-24** [comment]
Ok you mentiond 3.5 thats why i added this note :⁠-⁠)

Whats about admin tools? Within your setting of the plugin that you shared above there is an extra `#` before the header. As long that this is there the header will not be set. :⁠-⁠)

**Comment by marvays** [comment]
rofl.... # is problem. i am noob. sry. now all work! Thx

**Comment by zero-24** [comment]
No Problem will close this issue now :⁠-⁠)
