### ISSUE TITLE
Suggestion: CSP raw paste

### ISSUE THREAD

**Issue by JurgenG** [zero-24/plg_system_httpheader#7]
Hi,

there's a great tool out there for Firefox that helps you set a base line for your CSP settings for a given site. It's really handy because it gives a great starting point.
https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/
It would be nice if the tool would be able to just accept the copied result from the addon and parse it... into a raw reply or into separate items.

Anyway, kudos and thank you for this addon!

**Comment by zero-24** [comment]
Hi,

this is already possible you can set the Content-Security-Policy directly using the `Define additional HTTP Header` - Option. Please check the following screenshot:

![image](https://user-images.githubusercontent.com/2596554/53293272-334eb700-37d1-11e9-88c8-1ce4e8aad666.png)
