### ISSUE TITLE
Double headers if site cache plugin is enabled

### ISSUE THREAD

**Issue by ghost** [zero-24/plg_system_httpheader#9]
If you have enabled the site cache plugin, headers are set double at second page reload.

**What I was expect was that headers are set only once like this:**
![correct_headres](https://user-images.githubusercontent.com/37540795/55011525-475f2180-4fe6-11e9-8f63-73a3b458b9ee.png)

**What I got is this**
![double_headers_1](https://user-images.githubusercontent.com/37540795/55011602-63fb5980-4fe6-11e9-9dad-53473be2cc1a.png)
![double_headers_2](https://user-images.githubusercontent.com/37540795/55011606-65c51d00-4fe6-11e9-9575-e85b42ccf75f.png)

**How to reproduce**
Just activate the site cache plugin and reload the site twice
Checked on multiple sites

If you disable the site cache plugin, headers are set as expected at every reload

**My environment**
PHP 7.2.10 FPM-CGI
Apache 2.4
MySQL 5.7
Cache backend: APCu

**Comment by zero-24** [comment]
Ok seams to be an core issue as the security headers are not in the list of the singleValueResponseHeaders. PR: https://github.com/joomla/joomla-cms/pull/24429

Closing as there is a CMS PR please test that so we can hopefully get that in 3.9.5 planed for 09.04.
